### ISSUE TITLE
Please add alc236

### ISSUE THREAD

**Issue by Lorys89** [HowNeft/ComboJack#1]
Hi I have two Dell laptops, both with alc236
In both does not go the mic part of the combojack
Dump Dell vostro 5401
https://github.com/Lorys89/DELL_VOSTRO_5401-ICE-LAKE/blob/main/TOOLS%20EFI%20MOD/codec_dump.txt
https://github.com/Lorys89/DELL_VOSTRO_5401-ICE-LAKE/blob/main/TOOLS%20EFI%20MOD/codec_dump2.txt
Please help me

**Comment by hoaug-tran** [comment]
hmm, long time i dont touch to this, if you just want audio,mic working i can help you, And if you want to add it to Combojack, I probably can't do it now, sorry

**Comment by Lorys89** [comment]
> hmm, long time i dont touch to this, if you just want audio,mic working i can help you, And if you want to add it to Combojack, I probably can't do it now, sorry

Works audio speakers, works internal microphone, works combojack part headphone but not part microphone
